### ISSUE TITLE
creación  del mapeo del sitio web

### ISSUE THREAD

**Issue by ezefalzoi** [AnaEM219/Proyecto-Modulo-Full-Stack-TSDWAD#10]

**Comment by AnaEM219** [comment]
crear el mapa del sitio

**Comment by marianobraulio** [comment]
> crear el mapa del sitio 

Hola Ana, cómo estás? Se ven los cambios que hice?

**Comment by marianobraulio** [comment]
> > crear el mapa del sitio 
> 
> Hola Ana, cómo estás? Se ven los cambios que hice? 

@AnaEM219
